name = input ("Введите имя: ")
second_name =input("Введите фамилию: ")
year = int(input("Введите год рождения: "))
print (name+"_"+second_name+"_"+str(year))
print (second_name+"_"+name+"_"+str(year+60))